Load Libraries and Data

In [127]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [128]:
gun_data = pd.read_excel('data/gun_data.xlsx')
census_data = pd.read_csv('data/U.S. Census Data.csv')

In [129]:
gun_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12485 entries, 0 to 12484
Data columns (total 27 columns):
month                        12485 non-null object
state                        12485 non-null object
permit                       12461 non-null float64
permit_recheck               1100 non-null float64
handgun                      12465 non-null float64
long_gun                     12466 non-null float64
other                        5500 non-null float64
multiple                     12485 non-null int64
admin                        12462 non-null float64
prepawn_handgun              10542 non-null float64
prepawn_long_gun             10540 non-null float64
prepawn_other                5115 non-null float64
redemption_handgun           10545 non-null float64
redemption_long_gun          10544 non-null float64
redemption_other             5115 non-null float64
returned_handgun             2200 non-null float64
returned_long_gun            2145 non-null float64
returned_other               1815 non-null float64
rentals_handgun              990 non-null float64
rentals_long_gun             825 non-null float64
private_sale_handgun         2750 non-null float64
private_sale_long_gun        2750 non-null float64
private_sale_other           2750 non-null float64
return_to_seller_handgun     2475 non-null float64
return_to_seller_long_gun    2750 non-null float64
return_to_seller_other       2255 non-null float64
totals                       12485 non-null int64
dtypes: float64(23), int64(2), object(2)
memory usage: 2.6+ MB

In [130]:
census_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 52 columns):
Fact              80 non-null object
Fact Note         28 non-null object
Alabama           65 non-null object
Alaska            65 non-null object
Arizona           65 non-null object
Arkansas          65 non-null object
California        65 non-null object
Colorado          65 non-null object
Connecticut       65 non-null object
Delaware          65 non-null object
Florida           65 non-null object
Georgia           65 non-null object
Hawaii            65 non-null object
Idaho             65 non-null object
Illinois          65 non-null object
Indiana           65 non-null object
Iowa              65 non-null object
Kansas            65 non-null object
Kentucky          65 non-null object
Louisiana         65 non-null object
Maine             65 non-null object
Maryland          65 non-null object
Massachusetts     65 non-null object
Michigan          65 non-null object
Minnesota         65 non-null object
Mississippi       65 non-null object
Missouri          65 non-null object
Montana           65 non-null object
Nebraska          65 non-null object
Nevada            65 non-null object
New Hampshire     65 non-null object
New Jersey        65 non-null object
New Mexico        65 non-null object
New York          65 non-null object
North Carolina    65 non-null object
North Dakota      65 non-null object
Ohio              65 non-null object
Oklahoma          65 non-null object
Oregon            65 non-null object
Pennsylvania      65 non-null object
Rhode Island      65 non-null object
South Carolina    65 non-null object
South Dakota      65 non-null object
Tennessee         65 non-null object
Texas             65 non-null object
Utah              65 non-null object
Vermont           65 non-null object
Virginia          65 non-null object
Washington        65 non-null object
West Virginia     65 non-null object
Wisconsin         65 non-null object
Wyoming           65 non-null object
dtypes: object(52)
memory usage: 34.6+ KB

Begin Cleaning Census Data

In [146]:
census_data.head()

Fact,"Population estimates, July 1, 2016, (V2016)","Population estimates base, April 1, 2010, (V2016)","Population, percent change - April 1, 2010 (estimates base) to July 1, 2016, (V2016)","Population, Census, April 1, 2010","Persons under 5 years, percent, July 1, 2016, (V2016)","Persons under 5 years, percent, April 1, 2010","Persons under 18 years, percent, July 1, 2016, (V2016)","Persons under 18 years, percent, April 1, 2010","Persons 65 years and over, percent, July 1, 2016, (V2016)","Persons 65 years and over, percent, April 1, 2010",...,"All firms, 2012","Men-owned firms, 2012","Women-owned firms, 2012","Minority-owned firms, 2012","Nonminority-owned firms, 2012","Veteran-owned firms, 2012","Nonveteran-owned firms, 2012","Population per square mile, 2010","Land area in square miles, 2010",FIPS Code
Fact Note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alabama,"4,863,300","4,780,131",1.70%,"4,779,736",6.00%,6.40%,22.60%,23.70%,16.10%,13.80%,...,"374,153","203,604","137,630","92,219","272,651","41,943","316,984",94.4,"50,645.33","""01"""
Alaska,"741,894","710,249",4.50%,"710,231",7.30%,7.60%,25.20%,26.40%,10.40%,7.70%,...,"68,032","35,402","22,141","13,688","51,147","7,953","56,091",1.2,"570,640.95","""02"""
Arizona,"6,931,071","6,392,301",8.40%,"6,392,017",6.30%,7.10%,23.50%,25.50%,16.90%,13.80%,...,"499,926","245,243","182,425","135,313","344,981","46,780","427,582",56.3,"113,594.08","""04"""
Arkansas,"2,988,248","2,916,025",2.50%,"2,915,918",6.40%,6.80%,23.60%,24.40%,16.30%,14.40%,...,"231,959","123,158","75,962","35,982","189,029","25,915","192,988",56,"52,035.48","""05"""

In [147]:
census_data.tail()

Fact,"Population estimates, July 1, 2016, (V2016)","Population estimates base, April 1, 2010, (V2016)","Population, percent change - April 1, 2010 (estimates base) to July 1, 2016, (V2016)","Population, Census, April 1, 2010","Persons under 5 years, percent, July 1, 2016, (V2016)","Persons under 5 years, percent, April 1, 2010","Persons under 18 years, percent, July 1, 2016, (V2016)","Persons under 18 years, percent, April 1, 2010","Persons 65 years and over, percent, July 1, 2016, (V2016)","Persons 65 years and over, percent, April 1, 2010",...,"All firms, 2012","Men-owned firms, 2012","Women-owned firms, 2012","Minority-owned firms, 2012","Nonminority-owned firms, 2012","Veteran-owned firms, 2012","Nonveteran-owned firms, 2012","Population per square mile, 2010","Land area in square miles, 2010",FIPS Code
Virginia,"8,411,808","8,001,041",5.10%,"8,001,024",6.10%,6.40%,22.20%,23.20%,14.60%,12.20%,...,"653,193","353,012","236,290","185,043","450,109","76,434","548,439",202.6,"39,490.09","""51"""
Washington,"7,288,000","6,724,545",8.40%,"6,724,540",6.20%,6.50%,22.40%,23.50%,14.80%,12.30%,...,"541,522","262,650","187,677","92,807","426,697","49,331","461,401",101.2,"66,455.52","""53"""
West Virginia,"1,831,102","1,853,011",-1.20%,"1,852,994",5.50%,5.60%,20.50%,20.90%,18.80%,16.00%,...,"114,435","63,112","39,065","5,777","104,785","12,912","94,960",77.1,"24,038.21","""54"""
Wisconsin,"5,778,708","5,687,289",1.60%,"5,686,986",5.80%,6.30%,22.30%,23.60%,16.10%,13.70%,...,"432,980","236,252","133,859","40,507","379,934","39,830","370,755",105,"54,157.80","""55"""
Wyoming,"585,501","563,767",3.90%,"563,626",6.50%,7.10%,23.70%,24.00%,15.00%,12.40%,...,"62,427","30,039","19,344","4,077","55,397","6,470","51,353",5.8,"97,093.14","""56"""

Hmm, that's weird.  What's that junk data at the end of the file?

In [131]:
census_data.tail(30)

,Fact,Fact Note,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
55,"All firms, 2012",NaN,"374,153","68,032","499,926","231,959","3,548,449","547,352","326,693","73,418",...,81314,550453,"2,356,748","251,419","75,827","653,193","541,522","114,435","432,980","62,427"
56,"Men-owned firms, 2012",NaN,"203,604","35,402","245,243","123,158","1,852,580","284,554","187,845","38,328",...,42418,302249,"1,251,696","132,163","41,270","353,012","262,650","63,112","236,252","30,039"
57,"Women-owned firms, 2012",NaN,"137,630","22,141","182,425","75,962","1,320,085","194,508","106,678","23,964",...,23722,195694,"866,678","76,269","23,417","236,290","187,677","39,065","133,859","19,344"
58,"Minority-owned firms, 2012",NaN,"92,219","13,688","135,313","35,982","1,619,857","85,849","56,113","14,440",...,4101,105234,"1,070,392","24,423","2,354","185,043","92,807","5,777","40,507","4,077"
59,"Nonminority-owned firms, 2012",NaN,"272,651","51,147","344,981","189,029","1,819,107","442,365","259,614","54,782",...,74228,434025,"1,224,845","218,826","70,491","450,109","426,697","104,785","379,934","55,397"
60,"Veteran-owned firms, 2012",NaN,"41,943","7,953","46,780","25,915","252,377","51,722","31,056","7,206",...,8604,59379,"213,590","18,754","8,237","76,434","49,331","12,912","39,830","6,470"
61,"Nonveteran-owned firms, 2012",NaN,"316,984","56,091","427,582","192,988","3,176,341","469,524","281,182","60,318",...,66219,469392,"2,057,218","219,807","63,317","548,439","461,401","94,960","370,755","51,353"
62,"Population per square mile, 2010",NaN,94.4,1.2,56.3,56,239.1,48.5,738.1,460.8,...,10.7,153.9,96.3,33.6,67.9,202.6,101.2,77.1,105,5.8
63,"Land area in square miles, 2010",NaN,"50,645.33","570,640.95","113,594.08","52,035.48","155,779.22","103,641.89","4,842.36","1,948.54",...,75811,41234.9,"261,231.71","82,169.62","9,216.66","39,490.09","66,455.52","24,038.21","54,157.80","97,093.14"
64,FIPS Code,NaN,"""01""","""02""","""04""","""05""","""06""","""08""","""09""","""10""",...,"""46""","""47""","""48""","""49""","""50""","""51""","""53""","""54""","""55""","""56"""
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NOTE: FIPS Code values are enclosed in quotes ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Value Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,1,Includes data not distributed by county.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Fact Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,(a),Includes persons reporting only one race,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,(b),"Hispanics may be of any race, so also are incl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,(c),Economic Census - Puerto Rico data are not com...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Value Flags,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,-,Either no or too few sample observations were ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,D,Suppressed to avoid disclosure of confidential...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,F,Fewer than 25 firms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,FN,Footnote on this item in place of data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,Not available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,S,Suppressed; does not meet publication standards,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,X,Not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Z,Value greater than zero but less than half uni...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Let's try removing those from the data, before doing any sort of analysis

In [132]:
census_notes = census_data.iloc[67:84].copy()

In [133]:
census_data = census_data.iloc[:65]
census_data.shape

(65, 52)

In [134]:
census_data.tail()

,Fact,Fact Note,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
60,"Veteran-owned firms, 2012",NaN,"41,943","7,953","46,780","25,915","252,377","51,722","31,056","7,206",...,8604,59379,"213,590","18,754","8,237","76,434","49,331","12,912","39,830","6,470"
61,"Nonveteran-owned firms, 2012",NaN,"316,984","56,091","427,582","192,988","3,176,341","469,524","281,182","60,318",...,66219,469392,"2,057,218","219,807","63,317","548,439","461,401","94,960","370,755","51,353"
62,"Population per square mile, 2010",NaN,94.4,1.2,56.3,56,239.1,48.5,738.1,460.8,...,10.7,153.9,96.3,33.6,67.9,202.6,101.2,77.1,105,5.8
63,"Land area in square miles, 2010",NaN,"50,645.33","570,640.95","113,594.08","52,035.48","155,779.22","103,641.89","4,842.36","1,948.54",...,75811,41234.9,"261,231.71","82,169.62","9,216.66","39,490.09","66,455.52","24,038.21","54,157.80","97,093.14"
64,FIPS Code,NaN,"""01""","""02""","""04""","""05""","""06""","""08""","""09""","""10""",...,"""46""","""47""","""48""","""49""","""50""","""51""","""53""","""54""","""55""","""56"""

That's better!  Now, what was that data?

In [135]:
census_notes = census_notes.reset_index(drop=True)
census_notes

Interesting.  It looks like these are footnotes, presumably to reduce the data size?  Let's try replacing Fact Notes.

In [136]:
notes = census_notes.iloc[5:8][['Fact', 'Fact Note']]

notes = notes.set_index('Fact', drop=True)
notes

                                              Fact Note
Fact
(a)            Includes persons reporting only one race
(b)   Hispanics may be of any race, so also are incl...
(c)   Economic Census - Puerto Rico data are not com...

In [137]:
notes_map = notes.to_dict()['Fact Note']

In [138]:
notes_map

{'(a)': 'Includes persons reporting only one race',
 '(b)': 'Hispanics may be of any race, so also are included in applicable race categories',
 '(c)': 'Economic Census - Puerto Rico data are not comparable to U.S. Economic Census data'}

In [139]:
census_data['Fact Note'] = census_data['Fact Note'].map(notes_map)

In [140]:
census_data

,Fact,Fact Note,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,"Population estimates, July 1, 2016, (V2016)",NaN,"4,863,300","741,894","6,931,071","2,988,248","39,250,017","5,540,545","3,576,452","952,065",...,865454,6651194,"27,862,596","3,051,217","624,594","8,411,808","7,288,000","1,831,102","5,778,708","585,501"
1,"Population estimates base, April 1, 2010, (V2...",NaN,"4,780,131","710,249","6,392,301","2,916,025","37,254,522","5,029,324","3,574,114","897,936",...,814195,6346298,"25,146,100","2,763,888","625,741","8,001,041","6,724,545","1,853,011","5,687,289","563,767"
2,"Population, percent change - April 1, 2010 (es...",NaN,1.70%,4.50%,8.40%,2.50%,5.40%,10.20%,0.10%,6.00%,...,0.063,0.048,10.80%,10.40%,-0.20%,5.10%,8.40%,-1.20%,1.60%,3.90%
3,"Population, Census, April 1, 2010",NaN,"4,779,736","710,231","6,392,017","2,915,918","37,253,956","5,029,196","3,574,097","897,934",...,814180,6346105,"25,145,561","2,763,885","625,741","8,001,024","6,724,540","1,852,994","5,686,986","563,626"
4,"Persons under 5 years, percent, July 1, 2016, ...",NaN,6.00%,7.30%,6.30%,6.40%,6.30%,6.10%,5.20%,5.80%,...,0.071,0.061,7.20%,8.30%,4.90%,6.10%,6.20%,5.50%,5.80%,6.50%
5,"Persons under 5 years, percent, April 1, 2010",NaN,6.40%,7.60%,7.10%,6.80%,6.80%,6.80%,5.70%,6.20%,...,0.073,0.064,7.70%,9.50%,5.10%,6.40%,6.50%,5.60%,6.30%,7.10%
6,"Persons under 18 years, percent, July 1, 2016,...",NaN,22.60%,25.20%,23.50%,23.60%,23.20%,22.80%,21.10%,21.50%,...,0.246,0.226,26.20%,30.20%,19.00%,22.20%,22.40%,20.50%,22.30%,23.70%
7,"Persons under 18 years, percent, April 1, 2010",NaN,23.70%,26.40%,25.50%,24.40%,25.00%,24.40%,22.90%,22.90%,...,0.249,0.236,27.30%,31.50%,20.70%,23.20%,23.50%,20.90%,23.60%,24.00%
8,"Persons 65 years and over, percent, July 1, 2...",NaN,16.10%,10.40%,16.90%,16.30%,13.60%,13.40%,16.10%,17.50%,...,0.16,0.157,12.00%,10.50%,18.10%,14.60%,14.80%,18.80%,16.10%,15.00%
9,"Persons 65 years and over, percent, April 1, 2010",NaN,13.80%,7.70%,13.80%,14.40%,11.40%,10.90%,14.20%,14.40%,...,0.143,0.134,10.30%,9.00%,14.60%,12.20%,12.30%,16.00%,13.70%,12.40%
10,"Female persons, percent, July 1, 2016, (V2016)",NaN,51.60%,47.70%,50.30%,50.90%,50.30%,49.70%,51.20%,51.60%,...,0.496,0.512,50.40%,49.70%,50.60%,50.80%,50.00%,50.50%,50.30%,48.90%
11,"Female persons, percent, April 1, 2010",NaN,51.50%,48.00%,50.30%,50.90%,50.30%,49.90%,51.30%,51.60%,...,0.5,0.513,50.40%,49.80%,50.70%,50.90%,50.20%,50.70%,50.40%,49.00%
12,"White alone, percent, July 1, 2016, (V2016)",Includes persons reporting only one race,69.30%,66.10%,83.30%,79.40%,72.70%,87.50%,80.60%,70.10%,...,0.852,0.787,79.40%,91.10%,94.60%,70.00%,80.00%,93.60%,87.50%,92.80%
13,"Black or African American alone, percent, July...",Includes persons reporting only one race,26.80%,3.80%,4.90%,15.70%,6.50%,4.50%,11.80%,22.60%,...,0.02,0.171,12.60%,1.40%,1.30%,19.80%,4.10%,3.60%,6.60%,1.30%
14,"American Indian and Alaska Native alone, perce...",Includes persons reporting only one race,0.70%,15.20%,5.40%,1.00%,1.70%,1.60%,0.50%,0.60%,...,0.09,0.004,1.00%,1.60%,0.40%,0.50%,1.90%,0.20%,1.10%,2.70%
15,"Asian alone, percent, July 1, 2016, (V2016)",Includes persons reporting only one race,1.40%,6.30%,3.40%,1.60%,14.80%,3.30%,4.70%,4.00%,...,0.015,0.018,4.80%,2.50%,1.80%,6.60%,8.60%,0.80%,2.80%,1.00%
16,Native Hawaiian and Other Pacific Islander alo...,Includes persons reporting only one race,0.10%,1.30%,0.30%,0.30%,0.50%,0.20%,0.10%,0.10%,...,0.001,0.001,0.10%,1.00%,Z,0.10%,0.80%,Z,0.10%,0.10%
17,"Two or More Races, percent, July 1, 2016, (V2...",NaN,1.60%,7.30%,2.80%,2.00%,3.80%,3.00%,2.30%,2.60%,...,0.023,0.019,1.90%,2.50%,1.90%,2.90%,4.60%,1.70%,1.90%,2.10%
18,"Hispanic or Latino, percent, July 1, 2016, (V...","Hispanics may be of any race, so also are incl...",4.20%,7.00%,30.90%,7.30%,38.90%,21.30%,15.70%,9.20%,...,0.037,0.052,39.10%,13.80%,1.90%,9.10%,12.40%,1.50%,6.70%,10.00%
19,"White alone, not Hispanic or Latino, percent, ...",NaN,65.80%,61.20%,55.50%,72.90%,37.70%,68.60%,67.70%,62.90%,...,0.825,0.742,42.60%,78.80%,93.10%,62.40%,69.50%,92.30%,81.70%,84.10%
20,"Veterans, 2011-2015",NaN,"363,170","69,323","505,794","220,953","1,777,410","391,725","199,331","71,213",...,63742,462414,"1,539,655","134,332","44,708","706,539","564,864","150,021","381,940","48,505"
21,"Foreign born persons, percent, 2011-2015",NaN,3.50%,7.40%,13.50%,4.70%,27.00%,9.80%,13.90%,8.70%,...,0.03,0.048,16.60%,8.40%,4.30%,11.70%,13.40%,1.50%,4.80%,3.60%
22,"Housing units, July 1, 2016, (V2016)",NaN,"2,230,185","310,658","2,961,003","1,354,762","14,060,525","2,339,118","1,499,116","426,149",...,383838,2919671,"10,753,629","1,054,164","329,525","3,491,054","3,025,685","886,640","2,668,444","270,600"
23,"Housing units, April 1, 2010",NaN,"2,171,853","306,967","2,844,526","1,316,299","13,680,081","2,212,898","1,487,891","405,885",...,363438,2812133,"9,977,436","979,709","322,539","3,364,939","2,885,677","881,917","2,624,358","261,868"
24,"Owner-occupied housing unit rate, 2011-2015",NaN,68.70%,63.40%,62.80%,66.10%,54.30%,64.30%,67.00%,71.20%,...,0.681,0.668,62.20%,69.50%,71.00%,66.20%,62.50%,72.50%,67.30%,69.10%
25,"Median value of owner-occupied housing units, ...",NaN,"$125,500","$250,000","$167,500","$111,400","$385,500","$247,800","$270,500","$231,500",...,140500,142100,"$136,000","$215,900","$217,500","$245,000","$259,500","$103,800","$165,800","$194,800"
26,Median selected monthly owner costs -with a mo...,NaN,"$1,139","$1,827","$1,343","$1,019","$2,155","$1,577","$2,067","$1,537",...,1210,1181,"$1,432","$1,428","$1,535","$1,711","$1,731",$966,"$1,402","$1,348"
27,Median selected monthly owner costs -without a...,NaN,$345,$554,$380,$327,$500,$419,$833,$445,...,433,359,$460,$388,$641,$433,$511,$293,$532,$386
28,"Median gross rent, 2011-2015",NaN,$717,"$1,146",$913,$677,"$1,255","$1,002","$1,075","$1,018",...,655,764,$882,$887,$895,"$1,116","$1,014",$643,$776,$789
29,"Building permits, 2016",NaN,"15,001","1,503","35,578","9,474","102,350","38,974","5,504","5,804",...,5686,36157,"165,853","22,662","1,771","31,132","44,077","2,544","19,274","1,727"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,"Bachelor's degree or higher, percent of person...",NaN,23.50%,28.00%,27.50%,21.10%,31.40%,38.10%,37.60%,30.00%,...,0.27,0.249,27.60%,31.10%,36.00%,36.30%,32.90%,19.20%,27.80%,25.70%
36,"With a disability, under age 65 years, percent...",NaN,11.80%,8.10%,8.20%,12.30%,6.80%,7.20%,7.10%,8.50%,...,0.084,0.112,8.10%,6.60%,10.00%,7.70%,8.90%,14.40%,8.20%,8.50%
37,"Persons without health insurance, under age 6...",NaN,10.70%,15.50%,11.90%,9.30%,8.30%,8.60%,5.70%,6.60%,...,0.103,0.106,18.60%,9.70%,4.50%,10.10%,6.90%,6.50%,6.20%,13.40%
38,"In civilian labor force, total, percent of pop...",NaN,58.00%,67.70%,59.30%,58.50%,63.10%,67.60%,67.20%,63.10%,...,0.686,0.61,64.30%,67.70%,66.60%,64.70%,63.50%,53.90%,67.10%,67.70%
39,"In civilian labor force, female, percent of po...",NaN,53.00%,65.00%,54.50%,53.30%,57.20%,62.60%,62.80%,59.40%,...,0.646,0.563,57.70%,59.50%,63.60%,60.80%,58.50%,49.20%,63.50%,62.70%
40,"Total accommodation and food services sales, 2...",Economic Census - Puerto Rico data are not com...,"7,576,462","2,221,335","13,996,635","4,307,264","90,830,372","13,617,654","9,542,068","2,148,437",...,1873699,12499013,"54,480,811","4,789,281","1,564,272","17,795,901","14,297,278","4,036,333","10,303,256","1,644,844"
41,Total health care and social assistance receip...,Economic Census - Puerto Rico data are not com...,"26,039,632","6,375,483","37,055,881","15,792,628","248,953,592","29,488,161","29,573,119","7,003,251",...,6211731,42383683,"145,035,130","14,521,857","4,457,996","47,705,003","43,966,889","12,259,395","40,680,625","3,291,478"
42,"Total manufacturers shipments, 2012 ($1,000)",Economic Census - Puerto Rico data are not com...,"124,809,759",D,"51,243,473","62,712,925","512,303,164","50,447,098","55,160,095","22,597,384",...,16882647,139960482,"702,603,073","50,046,429","9,315,494","96,389,872","131,530,601","24,553,072","177,728,926","10,783,794"
43,"Total merchant wholesaler sales, 2012 ($1,000)",Economic Census - Puerto Rico data are not com...,"57,746,565","5,216,303","69,437,272","31,256,110","666,652,186","77,034,971","161,962,244","5,628,914",...,20411059,111718421,"691,242,607","30,927,885","6,450,076","86,613,641","83,313,366","14,295,437","77,066,883","5,597,891"
44,"Total retail sales, 2012 ($1,000)",Economic Census - Puerto Rico data are not com...,"58,564,965","10,474,275","84,716,542","36,815,256","481,800,461","67,815,200","51,632,467","14,456,001",...,13791827,91641605,"356,116,376","38,024,486","9,933,751","110,002,385","118,924,049","22,637,923","78,201,822","9,446,043"
45,"Total retail sales per capita, 2012",Economic Census - Puerto Rico data are not com...,"$12,145","$14,320","$12,927","$12,483","$12,665","$13,073","$14,381","$15,763",...,16550,14194,"$13,666","$13,317","$15,868","$13,438","$17,243","$12,201","$13,656","$16,388"
46,"Mean travel time to work (minutes), workers ag...",NaN,24.4,19,24.8,21.6,28,24.8,25.4,25.5,...,16.9,24.5,25.6,21.6,22.5,27.9,26.3,25.6,21.9,18.3
47,"Median household income (in 2015 dollars), 201...",NaN,"$43,623","$72,515","$50,255","$41,371","$61,818","$60,629","$70,331","$60,509",...,50957,45219,"$53,207","$60,727","$55,176","$65,015","$61,062","$41,751","$53,357","$58,840"
48,Per capita income in past 12 months (in 2015 d...,NaN,"$24,091","$33,413","$25,848","$22,798","$30,318","$32,217","$38,803","$30,554",...,26747,25227,"$26,999","$24,686","$29,894","$34,152","$31,762","$23,450","$28,340","$29,803"
49,"Persons in poverty, percent",NaN,17.10%,9.90%,16.40%,17.20%,14.30%,11.00%,9.80%,11.70%,...,0.133,0.158,15.60%,10.20%,11.90%,11.00%,11.30%,17.90%,11.80%,11.30%
50,"Total employer establishments, 2015",NaN,"98,540","20,907","136,352","65,175","908,120","161,737","89,232","24,852",...,26511,133344,"569,091","75,463","21,121","197,384","182,913","36,993","139,500","21,040"
51,"Total employment, 2015",NaN,"1,634,391","267,999","2,295,186","1,003,113","14,325,377","2,253,795","1,503,102","397,385",...,353540,2507205,"10,239,710","1,203,954","266,363","3,198,718","2,602,408","565,435","2,503,532","219,881"
52,"Total annual payroll, 2015 ($1,000)",NaN,"67,370,353","15,643,303","102,671,393","39,451,191","856,954,246","117,539,555","92,555,072","21,305,227",...,13812997,110481280,"521,095,797","51,453,266","10,615,093","165,788,897","149,258,789","22,159,084","112,406,494","10,094,010"
53,"Total employment, percent change, 2014-2015",NaN,1.90%,0.40%,2.40%,1.10%,3.50%,3.30%,1.20%,1.50%,...,0.016,0.022,3.20%,4.90%,2.00%,1.20%,2.90%,-1.70%,2.20%,FN
54,"Total nonemployer establishments, 2015",NaN,"322,025","55,521","451,951","198,380","3,206,958","480,847","272,809","60,734",...,64006,495703,"2,205,149","216,280","60,312","576,446","444,135","88,136","341,935","48,140"
55,"All firms, 2012",NaN,"374,153","68,032","499,926","231,959","3,548,449","547,352","326,693","73,418",...,81314,550453,"2,356,748","251,419","75,827","653,193","541,522","114,435","432,980","62,427"
56,"Men-owned firms, 2012",NaN,"203,604","35,402","245,243","123,158","1,852,580","284,554","187,845","38,328",...,42418,302249,"1,251,696","132,163","41,270","353,012","262,650","63,112","236,252","30,039"
57,"Women-owned firms, 2012",NaN,"137,630","22,141","182,425","75,962","1,320,085","194,508","106,678","23,964",...,23722,195694,"866,678","76,269","23,417","236,290","187,677","39,065","133,859","19,344"
58,"Minority-owned firms, 2012",NaN,"92,219","13,688","135,313","35,982","1,619,857","85,849","56,113","14,440",...,4101,105234,"1,070,392","24,423","2,354","185,043","92,807","5,777","40,507","4,077"
59,"Nonminority-owned firms, 2012",NaN,"272,651","51,147","344,981","189,029","1,819,107","442,365","259,614","54,782",...,74228,434025,"1,224,845","218,826","70,491","450,109","426,697","104,785","379,934","55,397"
60,"Veteran-owned firms, 2012",NaN,"41,943","7,953","46,780","25,915","252,377","51,722","31,056","7,206",...,8604,59379,"213,590","18,754","8,237","76,434","49,331","12,912","39,830","6,470"
61,"Nonveteran-owned firms, 2012",NaN,"316,984","56,091","427,582","192,988","3,176,341","469,524","281,182","60,318",...,66219,469392,"2,057,218","219,807","63,317","548,439","461,401","94,960","370,755","51,353"
62,"Population per square mile, 2010",NaN,94.4,1.2,56.3,56,239.1,48.5,738.1,460.8,...,10.7,153.9,96.3,33.6,67.9,202.6,101.2,77.1,105,5.8
63,"Land area in square miles, 2010",NaN,"50,645.33","570,640.95","113,594.08","52,035.48","155,779.22","103,641.89","4,842.36","1,948.54",...,75811,41234.9,"261,231.71","82,169.62","9,216.66","39,490.09","66,455.52","24,038.21","54,157.80","97,093.14"
64,FIPS Code,NaN,"""01""","""02""","""04""","""05""","""06""","""08""","""09""","""10""",...,"""46""","""47""","""48""","""49""","""50""","""51""","""53""","""54""","""55""","""56"""

That's better.  But state was a **field** in the gun data.  Better transpose the census_data to make it easier to join.

In [141]:
census_data.set_index('Fact', inplace=True)
census_data = census_data.transpose()

In [145]:
census_data

Fact,"Population estimates, July 1, 2016, (V2016)","Population estimates base, April 1, 2010, (V2016)","Population, percent change - April 1, 2010 (estimates base) to July 1, 2016, (V2016)","Population, Census, April 1, 2010","Persons under 5 years, percent, July 1, 2016, (V2016)","Persons under 5 years, percent, April 1, 2010","Persons under 18 years, percent, July 1, 2016, (V2016)","Persons under 18 years, percent, April 1, 2010","Persons 65 years and over, percent, July 1, 2016, (V2016)","Persons 65 years and over, percent, April 1, 2010",...,"All firms, 2012","Men-owned firms, 2012","Women-owned firms, 2012","Minority-owned firms, 2012","Nonminority-owned firms, 2012","Veteran-owned firms, 2012","Nonveteran-owned firms, 2012","Population per square mile, 2010","Land area in square miles, 2010",FIPS Code
Fact Note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alabama,"4,863,300","4,780,131",1.70%,"4,779,736",6.00%,6.40%,22.60%,23.70%,16.10%,13.80%,...,"374,153","203,604","137,630","92,219","272,651","41,943","316,984",94.4,"50,645.33","""01"""
Alaska,"741,894","710,249",4.50%,"710,231",7.30%,7.60%,25.20%,26.40%,10.40%,7.70%,...,"68,032","35,402","22,141","13,688","51,147","7,953","56,091",1.2,"570,640.95","""02"""
Arizona,"6,931,071","6,392,301",8.40%,"6,392,017",6.30%,7.10%,23.50%,25.50%,16.90%,13.80%,...,"499,926","245,243","182,425","135,313","344,981","46,780","427,582",56.3,"113,594.08","""04"""
Arkansas,"2,988,248","2,916,025",2.50%,"2,915,918",6.40%,6.80%,23.60%,24.40%,16.30%,14.40%,...,"231,959","123,158","75,962","35,982","189,029","25,915","192,988",56,"52,035.48","""05"""
California,"39,250,017","37,254,522",5.40%,"37,253,956",6.30%,6.80%,23.20%,25.00%,13.60%,11.40%,...,"3,548,449","1,852,580","1,320,085","1,619,857","1,819,107","252,377","3,176,341",239.1,"155,779.22","""06"""
Colorado,"5,540,545","5,029,324",10.20%,"5,029,196",6.10%,6.80%,22.80%,24.40%,13.40%,10.90%,...,"547,352","284,554","194,508","85,849","442,365","51,722","469,524",48.5,"103,641.89","""08"""
Connecticut,"3,576,452","3,574,114",0.10%,"3,574,097",5.20%,5.70%,21.10%,22.90%,16.10%,14.20%,...,"326,693","187,845","106,678","56,113","259,614","31,056","281,182",738.1,"4,842.36","""09"""
Delaware,"952,065","897,936",6.00%,"897,934",5.80%,6.20%,21.50%,22.90%,17.50%,14.40%,...,"73,418","38,328","23,964","14,440","54,782","7,206","60,318",460.8,"1,948.54","""10"""
Florida,"20,612,439","18,804,592",9.60%,"18,801,310",5.50%,5.70%,20.10%,21.30%,19.90%,17.30%,...,"2,100,187","1,084,885","807,817","926,112","1,121,749","185,756","1,846,686",350.6,"53,624.76","""12"""
Georgia,"10,310,371","9,688,680",6.40%,"9,687,653",6.40%,7.10%,24.40%,25.70%,13.10%,10.70%,...,"929,864","480,578","376,506","371,588","538,893","96,787","800,585",168.4,"57,513.49","""13"""
Hawaii,"1,428,557","1,360,301",5.00%,"1,360,301",6.40%,6.40%,21.60%,22.30%,17.10%,14.30%,...,"118,454","60,409","44,453","74,208","38,510","11,148","101,334",211.8,"6,422.63","""15"""
Idaho,"1,683,140","1,567,650",7.40%,"1,567,582",6.80%,7.80%,26.00%,27.40%,15.10%,12.40%,...,"146,642","70,438","45,121","10,592","130,973","12,804","124,314",19,"82,643.12","""16"""
Illinois,"12,801,539","12,831,574",-0.20%,"12,830,632",6.00%,6.50%,22.90%,24.40%,14.60%,12.50%,...,"1,135,017","609,648","417,500","311,684","795,129","89,110","1,006,885",231.1,"55,518.93","""17"""
Indiana,"6,633,053","6,484,136",2.30%,"6,483,802",6.40%,6.70%,23.80%,24.80%,14.90%,13.00%,...,"479,059","253,533","162,798","61,252","405,090","45,174","412,543",181,"35,826.11","""18"""
Iowa,"3,134,693","3,046,869",2.90%,"3,046,355",6.40%,6.60%,23.30%,23.90%,16.40%,14.90%,...,"259,121","135,382","82,345","14,707","236,561","25,889","217,779",54.5,"55,857.13","""19"""
Kansas,"2,907,289","2,853,129",1.90%,"2,853,118",6.70%,7.20%,24.60%,25.50%,15.00%,13.20%,...,"239,118","125,169","77,194","26,127","204,562","21,610","203,401",34.9,"81,758.72","""20"""
Kentucky,"4,436,974","4,339,344",2.20%,"4,339,367",6.20%,6.50%,22.80%,23.60%,15.60%,13.30%,...,"331,546","184,154","106,011","27,258","296,155","33,208","282,704",109.9,"39,486.34","""21"""
Louisiana,"4,681,666","4,533,479",3.30%,"4,533,372",6.60%,6.90%,23.80%,24.70%,14.40%,12.30%,...,"414,291","215,111","151,114","126,100","277,676","42,211","354,460",104.9,"43,203.90","""22"""
Maine,"1,331,479","1,328,364",0.20%,"1,328,361",4.90%,5.20%,19.10%,20.70%,19.40%,15.90%,...,"139,570","79,243","42,067","4,339","131,322","15,689","115,839",43.1,"30,842.92","""23"""
Maryland,"6,016,447","5,773,786",4.20%,"5,773,552",6.10%,6.30%,22.40%,23.40%,14.60%,12.30%,...,"531,953","276,630","209,119","203,394","314,902","50,976","462,232",594.8,"9,707.24","""24"""
Massachusetts,"6,811,779","6,547,813",4.00%,"6,547,629",5.30%,5.60%,20.20%,21.70%,15.80%,13.80%,...,"607,664","357,158","199,210","89,967","499,959","58,339","525,667",839.4,"7,800.06","""25"""
Michigan,"9,928,300","9,884,129",0.40%,"9,883,640",5.80%,6.00%,22.10%,23.70%,16.20%,13.80%,...,"834,087","446,128","306,986","158,946","657,237","71,861","733,517",174.8,"56,538.90","""26"""
Minnesota,"5,519,952","5,303,924",4.10%,"5,303,925",6.40%,6.70%,23.30%,24.20%,15.10%,12.90%,...,"489,494","268,710","157,821","47,302","428,716","45,582","419,628",66.6,"79,626.74","""27"""
Mississippi,"2,988,726","2,968,103",0.70%,"2,967,297",6.30%,7.10%,24.10%,25.50%,15.10%,12.80%,...,"235,454","125,079","89,159","74,824","155,094","26,789","198,566",63.2,"46,923.27","""28"""
Missouri,"6,093,000","5,988,928",1.70%,"5,988,927",6.10%,6.50%,22.80%,23.80%,16.10%,14.00%,...,"491,606","257,948","162,616","61,035","415,972","49,217","415,542",87.1,"68,741.52","""29"""
Montana,"1,042,520","989,414",5.40%,"989,415",6.00%,6.30%,21.80%,22.60%,17.70%,14.80%,...,"112,419","55,913","35,449","5,578","102,746","11,486","93,393",6.8,"145,545.80","""30"""
Nebraska,"1,907,116","1,826,334",4.40%,"1,826,341",7.00%,7.20%,24.80%,25.10%,15.00%,13.50%,...,"164,089","83,696","51,936","14,571","144,122","16,693","137,254",23.8,"76,824.17","""31"""
Nevada,"2,940,058","2,700,691",8.90%,"2,700,551",6.30%,6.90%,23.00%,24.60%,15.00%,12.00%,...,"227,156","114,057","82,508","71,864","144,944","23,049","191,293",24.6,"109,781.18","""32"""
New Hampshire,"1,334,795","1,316,461",1.40%,"1,316,470",4.80%,5.30%,19.50%,21.80%,17.00%,13.50%,...,"131,638","76,716","38,525","6,111","121,297","16,119","108,817",147,"8,952.65","""33"""
New Jersey,"8,944,469","8,791,953",1.70%,"8,791,894",5.80%,6.20%,22.20%,23.50%,15.30%,13.50%,...,"792,088","464,592","252,944","237,242","533,808","57,996","707,975","1,195.50","7,354.22","""34"""
New Mexico,2081015,2059198,0.011,2059179,0.062,0.07,0.236,0.252,0.165,0.132,...,151363,71132,59044,60622,83857,14096,128693,17,121298.15,"""35"""
New York,19745289,19378110,0.019,19378102,0.059,0.06,0.212,0.223,0.154,0.135,...,2008988,1139910,725709,709021,1248304,137532,1811544,411.2,47126.4,"""36"""
North Carolina,10146788,9535688,0.064,9535483,0.06,0.066,0.227,0.239,0.155,0.129,...,805985,435677,287058,183380,603182,86571,684743,196.1,48617.91,"""37"""
North Dakota,757952,672591,0.127,672591,0.073,0.066,0.233,0.223,0.145,0.145,...,68270,37016,20316,3190,62271,6584,56904,9.7,69000.8,"""38"""
Ohio,11614373,11536727,0.007,11536504,0.06,0.062,0.225,0.237,0.162,0.141,...,904814,510078,306824,122653,759569,91316,776193,282.3,40860.69,"""39"""
Oklahoma,3923561,3751615,0.046,3751351,0.068,0.07,0.245,0.248,0.15,0.135,...,327229,174395,105168,64875,249027,36273,273491,54.7,68594.92,"""40"""
Oregon,4093465,3831072,0.068,3831074,0.058,0.062,0.212,0.226,0.168,0.139,...,339305,165691,123015,41456,285028,30918,288790,39.9,95988.01,"""41"""
Pennsylvania,12784227,12702857,0.006,12702379,0.056,0.057,0.209,0.22,0.174,0.154,...,975453,579400,304803,131512,818858,97969,837792,283.9,44742.7,"""42"""
Rhode Island,1056426,1052940,0.003,1052567,0.052,0.055,0.197,0.213,0.165,0.144,...,94642,54651,30484,14737,77042,9904,79837,1018.1,1033.81,"""44"""
South Carolina,4961119,4625410,0.073,4625364,0.059,0.065,0.221,0.234,0.167,0.137,...,367726,202446,131856,83233,276269,47987,303137,153.9,30060.7,"""45"""
South Dakota,865454,814195,0.063,814180,0.071,0.073,0.246,0.249,0.16,0.143,...,81314,42418,23722,4101,74228,8604,66219,10.7,75811,"""46"""
Tennessee,6651194,6346298,0.048,6346105,0.061,0.064,0.226,0.236,0.157,0.134,...,550453,302249,195694,105234,434025,59379,469392,153.9,41234.9,"""47"""
Texas,"27,862,596","25,146,100",10.80%,"25,145,561",7.20%,7.70%,26.20%,27.30%,12.00%,10.30%,...,"2,356,748","1,251,696","866,678","1,070,392","1,224,845","213,590","2,057,218",96.3,"261,231.71","""48"""
Utah,"3,051,217","2,763,888",10.40%,"2,763,885",8.30%,9.50%,30.20%,31.50%,10.50%,9.00%,...,"251,419","132,163","76,269","24,423","218,826","18,754","219,807",33.6,"82,169.62","""49"""
Vermont,"624,594","625,741",-0.20%,"625,741",4.90%,5.10%,19.00%,20.70%,18.10%,14.60%,...,"75,827","41,270","23,417","2,354","70,491","8,237","63,317",67.9,"9,216.66","""50"""
Virginia,"8,411,808","8,001,041",5.10%,"8,001,024",6.10%,6.40%,22.20%,23.20%,14.60%,12.20%,...,"653,193","353,012","236,290","185,043","450,109","76,434","548,439",202.6,"39,490.09","""51"""
Washington,"7,288,000","6,724,545",8.40%,"6,724,540",6.20%,6.50%,22.40%,23.50%,14.80%,12.30%,...,"541,522","262,650","187,677","92,807","426,697","49,331","461,401",101.2,"66,455.52","""53"""
West Virginia,"1,831,102","1,853,011",-1.20%,"1,852,994",5.50%,5.60%,20.50%,20.90%,18.80%,16.00%,...,"114,435","63,112","39,065","5,777","104,785","12,912","94,960",77.1,"24,038.21","""54"""
Wisconsin,"5,778,708","5,687,289",1.60%,"5,686,986",5.80%,6.30%,22.30%,23.60%,16.10%,13.70%,...,"432,980","236,252","133,859","40,507","379,934","39,830","370,755",105,"54,157.80","""55"""
Wyoming,"585,501","563,767",3.90%,"563,626",6.50%,7.10%,23.70%,24.00%,15.00%,12.40%,...,"62,427","30,039","19,344","4,077","55,397","6,470","51,353",5.8,"97,093.14","""56"""

That's better, although all that work converting the Fact Notes will be less than useful since it won't carry over.  Also, for now we're disregarding the Value Flags

In [166]:
census_data.iloc[0].dropna()

Fact
White alone, percent, July 1, 2016,  (V2016)                                                  Includes persons reporting only one race
Black or African American alone, percent, July 1, 2016,  (V2016)                              Includes persons reporting only one race
American Indian and Alaska Native alone, percent, July 1, 2016,  (V2016)                      Includes persons reporting only one race
Asian alone, percent, July 1, 2016,  (V2016)                                                  Includes persons reporting only one race
Native Hawaiian and Other Pacific Islander alone, percent, July 1, 2016,  (V2016)             Includes persons reporting only one race
Hispanic or Latino, percent, July 1, 2016,  (V2016)                                  Hispanics may be of any race, so also are incl...
Total accommodation and food services sales, 2012 ($1,000)                           Economic Census - Puerto Rico data are not com...
Total health care and social assistance receipts/revenue, 2012 ($1,000)              Economic Census - Puerto Rico data are not com...
Total manufacturers shipments, 2012 ($1,000)                                         Economic Census - Puerto Rico data are not com...
Total merchant wholesaler sales, 2012 ($1,000)                                       Economic Census - Puerto Rico data are not com...
Total retail sales, 2012 ($1,000)                                                    Economic Census - Puerto Rico data are not com...
Total retail sales per capita, 2012                                                  Economic Census - Puerto Rico data are not com...
Name: Fact Note, dtype: object

Begin Cleaning Gun Data

In [168]:
gun_data.head()

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,returned_other,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals
0,2017-09,Alabama,16717.0,0.0,5734.0,6320.0,221.0,317,0.0,15.0,...,0.0,0.0,0.0,9.0,16.0,3.0,0.0,0.0,3.0,32019
1,2017-09,Alaska,209.0,2.0,2320.0,2930.0,219.0,160,0.0,5.0,...,0.0,0.0,0.0,17.0,24.0,1.0,0.0,0.0,0.0,6303
2,2017-09,Arizona,5069.0,382.0,11063.0,7946.0,920.0,631,0.0,13.0,...,0.0,0.0,0.0,38.0,12.0,2.0,0.0,0.0,0.0,28394
3,2017-09,Arkansas,2935.0,632.0,4347.0,6063.0,165.0,366,51.0,12.0,...,0.0,0.0,0.0,13.0,23.0,0.0,0.0,2.0,1.0,17747
4,2017-09,California,57839.0,0.0,37165.0,24581.0,2984.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,123506

In [169]:
gun_data.tail()

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,returned_other,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals
12480,1998-11,Virginia,0.0,NaN,14.0,2.0,NaN,8,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
12481,1998-11,Washington,1.0,NaN,65.0,286.0,NaN,8,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361
12482,1998-11,West Virginia,3.0,NaN,149.0,251.0,NaN,5,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,408
12483,1998-11,Wisconsin,0.0,NaN,25.0,214.0,NaN,2,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,241
12484,1998-11,Wyoming,8.0,NaN,45.0,49.0,NaN,5,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107

There's nothing immediately apparently wrong.  Let's join the two datasets.

In [170]:
combined_data = gun_data.join(census_data, on='state')
combined_data

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,"All firms, 2012","Men-owned firms, 2012","Women-owned firms, 2012","Minority-owned firms, 2012","Nonminority-owned firms, 2012","Veteran-owned firms, 2012","Nonveteran-owned firms, 2012","Population per square mile, 2010","Land area in square miles, 2010",FIPS Code
0,2017-09,Alabama,16717.0,0.0,5734.0,6320.0,221.0,317,0.0,15.0,...,"374,153","203,604","137,630","92,219","272,651","41,943","316,984",94.4,"50,645.33","""01"""
1,2017-09,Alaska,209.0,2.0,2320.0,2930.0,219.0,160,0.0,5.0,...,"68,032","35,402","22,141","13,688","51,147","7,953","56,091",1.2,"570,640.95","""02"""
2,2017-09,Arizona,5069.0,382.0,11063.0,7946.0,920.0,631,0.0,13.0,...,"499,926","245,243","182,425","135,313","344,981","46,780","427,582",56.3,"113,594.08","""04"""
3,2017-09,Arkansas,2935.0,632.0,4347.0,6063.0,165.0,366,51.0,12.0,...,"231,959","123,158","75,962","35,982","189,029","25,915","192,988",56,"52,035.48","""05"""
4,2017-09,California,57839.0,0.0,37165.0,24581.0,2984.0,0,0.0,0.0,...,"3,548,449","1,852,580","1,320,085","1,619,857","1,819,107","252,377","3,176,341",239.1,"155,779.22","""06"""
5,2017-09,Colorado,4356.0,0.0,15751.0,13448.0,1007.0,1062,0.0,0.0,...,"547,352","284,554","194,508","85,849","442,365","51,722","469,524",48.5,"103,641.89","""08"""
6,2017-09,Connecticut,4343.0,673.0,4834.0,1993.0,274.0,0,0.0,0.0,...,"326,693","187,845","106,678","56,113","259,614","31,056","281,182",738.1,"4,842.36","""09"""
7,2017-09,Delaware,275.0,0.0,1414.0,1538.0,66.0,68,0.0,0.0,...,"73,418","38,328","23,964","14,440","54,782","7,206","60,318",460.8,"1,948.54","""10"""
8,2017-09,District of Columbia,1.0,0.0,56.0,4.0,0.0,0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2017-09,Florida,10784.0,0.0,39199.0,17949.0,2319.0,1721,1.0,18.0,...,"2,100,187","1,084,885","807,817","926,112","1,121,749","185,756","1,846,686",350.6,"53,624.76","""12"""
10,2017-09,Georgia,12074.0,0.0,10933.0,7982.0,315.0,494,0.0,20.0,...,"929,864","480,578","376,506","371,588","538,893","96,787","800,585",168.4,"57,513.49","""13"""
11,2017-09,Guam,0.0,0.0,74.0,47.0,10.0,3,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2017-09,Hawaii,946.0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,"118,454","60,409","44,453","74,208","38,510","11,148","101,334",211.8,"6,422.63","""15"""
13,2017-09,Idaho,5162.0,0.0,3058.0,5241.0,187.0,205,0.0,0.0,...,"146,642","70,438","45,121","10,592","130,973","12,804","124,314",19,"82,643.12","""16"""
14,2017-09,Illinois,15712.0,71432.0,18290.0,10201.0,0.0,814,0.0,0.0,...,"1,135,017","609,648","417,500","311,684","795,129","89,110","1,006,885",231.1,"55,518.93","""17"""
15,2017-09,Indiana,18241.0,0.0,16093.0,11332.0,1123.0,597,79.0,5.0,...,"479,059","253,533","162,798","61,252","405,090","45,174","412,543",181,"35,826.11","""18"""
16,2017-09,Iowa,5847.0,1217.0,151.0,2640.0,27.0,1,1.0,0.0,...,"259,121","135,382","82,345","14,707","236,561","25,889","217,779",54.5,"55,857.13","""19"""
17,2017-09,Kansas,1567.0,3.0,4518.0,5025.0,306.0,297,0.0,3.0,...,"239,118","125,169","77,194","26,127","204,562","21,610","203,401",34.9,"81,758.72","""20"""
18,2017-09,Kentucky,378384.0,0.0,8112.0,7543.0,253.0,543,1.0,16.0,...,"331,546","184,154","106,011","27,258","296,155","33,208","282,704",109.9,"39,486.34","""21"""
19,2017-09,Louisiana,1827.0,0.0,10495.0,11573.0,635.0,776,0.0,6.0,...,"414,291","215,111","151,114","126,100","277,676","42,211","354,460",104.9,"43,203.90","""22"""
20,2017-09,Maine,783.0,0.0,3026.0,4220.0,179.0,186,1.0,0.0,...,"139,570","79,243","42,067","4,339","131,322","15,689","115,839",43.1,"30,842.92","""23"""
21,2017-09,Mariana Islands,0.0,0.0,12.0,3.0,0.0,1,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2017-09,Maryland,2424.0,0.0,3389.0,4897.0,168.0,34,0.0,0.0,...,"531,953","276,630","209,119","203,394","314,902","50,976","462,232",594.8,"9,707.24","""24"""
23,2017-09,Massachusetts,7160.0,0.0,4749.0,2808.0,449.0,158,0.0,0.0,...,"607,664","357,158","199,210","89,967","499,959","58,339","525,667",839.4,"7,800.06","""25"""
24,2017-09,Michigan,16571.0,19.0,8654.0,10676.0,379.0,163,0.0,1.0,...,"834,087","446,128","306,986","158,946","657,237","71,861","733,517",174.8,"56,538.90","""26"""
25,2017-09,Minnesota,25645.0,0.0,4862.0,12677.0,346.0,273,0.0,1.0,...,"489,494","268,710","157,821","47,302","428,716","45,582","419,628",66.6,"79,626.74","""27"""
26,2017-09,Mississippi,1362.0,0.0,6260.0,6035.0,206.0,405,0.0,33.0,...,"235,454","125,079","89,159","74,824","155,094","26,789","198,566",63.2,"46,923.27","""28"""
27,2017-09,Missouri,791.0,0.0,16993.0,14395.0,1050.0,991,0.0,12.0,...,"491,606","257,948","162,616","61,035","415,972","49,217","415,542",87.1,"68,741.52","""29"""
28,2017-09,Montana,1076.0,0.0,2395.0,4878.0,140.0,216,3.0,4.0,...,"112,419","55,913","35,449","5,578","102,746","11,486","93,393",6.8,"145,545.80","""30"""
29,2017-09,Nebraska,3036.0,113.0,110.0,1989.0,11.0,4,0.0,0.0,...,"164,089","83,696","51,936","14,571","144,122","16,693","137,254",23.8,"76,824.17","""31"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12455,1998-11,Minnesota,9.0,NaN,27.0,280.0,NaN,3,0.0,NaN,...,"489,494","268,710","157,821","47,302","428,716","45,582","419,628",66.6,"79,626.74","""27"""
12456,1998-11,Mississippi,0.0,NaN,286.0,491.0,NaN,7,0.0,NaN,...,"235,454","125,079","89,159","74,824","155,094","26,789","198,566",63.2,"46,923.27","""28"""
12457,1998-11,Missouri,0.0,NaN,116.0,458.0,NaN,4,0.0,NaN,...,"491,606","257,948","162,616","61,035","415,972","49,217","415,542",87.1,"68,741.52","""29"""
12458,1998-11,Montana,0.0,NaN,101.0,98.0,NaN,2,0.0,NaN,...,"112,419","55,913","35,449","5,578","102,746","11,486","93,393",6.8,"145,545.80","""30"""
12459,1998-11,Nebraska,88.0,NaN,1.0,96.0,NaN,1,0.0,NaN,...,"164,089","83,696","51,936","14,571","144,122","16,693","137,254",23.8,"76,824.17","""31"""
12460,1998-11,Nevada,0.0,NaN,75.0,76.0,NaN,8,0.0,NaN,...,"227,156","114,057","82,508","71,864","144,944","23,049","191,293",24.6,"109,781.18","""32"""
12461,1998-11,New Hampshire,0.0,NaN,8.0,46.0,NaN,1,0.0,NaN,...,"131,638","76,716","38,525","6,111","121,297","16,119","108,817",147,"8,952.65","""33"""
12462,1998-11,New Jersey,0.0,NaN,20.0,53.0,NaN,2,2.0,NaN,...,"792,088","464,592","252,944","237,242","533,808","57,996","707,975","1,195.50","7,354.22","""34"""
12463,1998-11,New Mexico,0.0,NaN,86.0,121.0,NaN,4,0.0,NaN,...,151363,71132,59044,60622,83857,14096,128693,17,121298.15,"""35"""
12464,1998-11,New York,0.0,NaN,40.0,279.0,NaN,0,0.0,NaN,...,2008988,1139910,725709,709021,1248304,137532,1811544,411.2,47126.4,"""36"""
12465,1998-11,North Carolina,524.0,NaN,87.0,695.0,NaN,4,0.0,NaN,...,805985,435677,287058,183380,603182,86571,684743,196.1,48617.91,"""37"""
12466,1998-11,North Dakota,0.0,NaN,20.0,38.0,NaN,0,0.0,NaN,...,68270,37016,20316,3190,62271,6584,56904,9.7,69000.8,"""38"""
12467,1998-11,Ohio,0.0,NaN,502.0,434.0,NaN,16,0.0,NaN,...,904814,510078,306824,122653,759569,91316,776193,282.3,40860.69,"""39"""
12468,1998-11,Oklahoma,0.0,NaN,259.0,361.0,NaN,13,0.0,NaN,...,327229,174395,105168,64875,249027,36273,273491,54.7,68594.92,"""40"""
12469,1998-11,Oregon,0.0,NaN,153.0,186.0,NaN,5,0.0,NaN,...,339305,165691,123015,41456,285028,30918,288790,39.9,95988.01,"""41"""
12470,1998-11,Pennsylvania,0.0,NaN,5.0,8.0,NaN,4,0.0,NaN,...,975453,579400,304803,131512,818858,97969,837792,283.9,44742.7,"""42"""
12471,1998-11,Puerto Rico,0.0,NaN,1.0,1.0,NaN,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12472,1998-11,Rhode Island,0.0,NaN,13.0,23.0,NaN,2,0.0,NaN,...,94642,54651,30484,14737,77042,9904,79837,1018.1,1033.81,"""44"""
12473,1998-11,South Carolina,0.0,NaN,0.0,6.0,NaN,0,0.0,NaN,...,367726,202446,131856,83233,276269,47987,303137,153.9,30060.7,"""45"""
12474,1998-11,South Dakota,0.0,NaN,8.0,66.0,NaN,0,0.0,NaN,...,81314,42418,23722,4101,74228,8604,66219,10.7,75811,"""46"""
12475,1998-11,Tennessee,0.0,NaN,19.0,85.0,NaN,3,0.0,NaN,...,550453,302249,195694,105234,434025,59379,469392,153.9,41234.9,"""47"""
12476,1998-11,Texas,0.0,NaN,1384.0,1349.0,NaN,60,1.0,NaN,...,"2,356,748","1,251,696","866,678","1,070,392","1,224,845","213,590","2,057,218",96.3,"261,231.71","""48"""
12477,1998-11,Utah,0.0,NaN,98.0,169.0,NaN,0,0.0,NaN,...,"251,419","132,163","76,269","24,423","218,826","18,754","219,807",33.6,"82,169.62","""49"""
12478,1998-11,Vermont,0.0,NaN,23.0,35.0,NaN,0,1.0,NaN,...,"75,827","41,270","23,417","2,354","70,491","8,237","63,317",67.9,"9,216.66","""50"""
12479,1998-11,Virgin Islands,0.0,NaN,0.0,0.0,NaN,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12480,1998-11,Virginia,0.0,NaN,14.0,2.0,NaN,8,0.0,NaN,...,"653,193","353,012","236,290","185,043","450,109","76,434","548,439",202.6,"39,490.09","""51"""
12481,1998-11,Washington,1.0,NaN,65.0,286.0,NaN,8,1.0,NaN,...,"541,522","262,650","187,677","92,807","426,697","49,331","461,401",101.2,"66,455.52","""53"""
12482,1998-11,West Virginia,3.0,NaN,149.0,251.0,NaN,5,0.0,NaN,...,"114,435","63,112","39,065","5,777","104,785","12,912","94,960",77.1,"24,038.21","""54"""
12483,1998-11,Wisconsin,0.0,NaN,25.0,214.0,NaN,2,0.0,NaN,...,"432,980","236,252","133,859","40,507","379,934","39,830","370,755",105,"54,157.80","""55"""
12484,1998-11,Wyoming,8.0,NaN,45.0,49.0,NaN,5,0.0,NaN,...,"62,427","30,039","19,344","4,077","55,397","6,470","51,353",5.8,"97,093.14","""56"""